// Auto-generated comprehensive site assets for preloader and background cache
export const PRELOAD_ASSETS: string[] = [
  "/404.webp",
  "/AboutUs/about-hero-icons/acres-icon.svg",
  "/AboutUs/about-hero-icons/kg-icon.svg",
  "/AboutUs/about-hero-icons/sq-ft-icon.svg",
  "/AboutUs/about-hero-icons/tons-icon.svg",
  "/AboutUs/about-hero-icons/vehicles-icon.svg",
  "/AboutUs/about-hero-img.webp",
  "/AboutUs/about-us-hero-image.webp",
  "/AboutUs/heroimage.webp",
  "/AboutUs/keralas-original.webp",
  "/AboutUs/mission-bg.webp",
  "/AboutUs/mission-image.webp",
  "/AboutUs/mission-vision/mission-text.svg",
  "/AboutUs/mission-vision/vision-text.svg",
  "/AboutUs/our-values-icons/customer-satisfaction-icon.svg",
  "/AboutUs/our-values-icons/freshness-icon.svg",
  "/AboutUs/our-values-icons/quality-icon.svg",
  "/AboutUs/our-values-icons/trust-icon.svg",
  "/AboutUs/quality-is-our-promise.webp",
  "/AboutUs/vision-bg.webp",
  "/AboutUs/who-is-bg.webp",
  "/AboutUs/who-is-image.webp",
  "/AboutUs/who-is-meatin-icons/export-quality.svg",
  "/AboutUs/who-is-meatin-icons/halal-certified.svg",
  "/AboutUs/who-is-meatin-icons/hygienic-production.svg",
  "/AboutUs/who-is-meatin-icons/scientific-procssing.svg",
  "/CareersBanner/careers-arrow.svg",
  "/CareersBanner/careers-left-bg.webp",
  "/CareersBanner/careers_image.webp",
  "/ContactUs/banner-img.webp",
  "/ContactUs/careers-banner.svg",
  "/ContactUs/contact-banner-mobile-image.webp",
  "/ContactUs/contact-banner-people-image.png",
  "/ContactUs/contact-banner-people-image.webp",
  "/ContactUs/contact-us-bg.webp",
  "/ContactUs/contact-us-icons/address-icon.svg",
  "/ContactUs/contact-us-icons/bitcoin-icons_share-filled.svg",
  "/ContactUs/contact-us-icons/dedicated-support.svg",
  "/ContactUs/contact-us-icons/email-icon.svg",
  "/ContactUs/contact-us-icons/email-outline.svg",
  "/ContactUs/contact-us-icons/enquiry-type.svg",
  "/ContactUs/contact-us-icons/faq-icon.svg",
  "/ContactUs/contact-us-icons/full-name-icon.svg",
  "/ContactUs/contact-us-icons/headset-icon.svg",
  "/ContactUs/contact-us-icons/message-icon.svg",
  "/ContactUs/contact-us-icons/phone-icon.svg",
  "/ContactUs/contact-us-icons/safeguard-outline.svg",
  "/ContactUs/contact-us-icons/whatsapp-icon.svg",
  "/Footer/call.webp",
  "/Footer/doodle.webp",
  "/Footer/facebook.webp",
  "/Footer/instagram.webp",
  "/Footer/location.webp",
  "/Footer/mail.webp",
  "/Footer/rightside.webp",
  "/Footer/whatsapp.webp",
  "/Footer/youtuble.webp",
  "/Franchies/bg-pattern-layer.webp",
  "/Franchies/bg.webp",
  "/Franchies/bottomSlope.webp",
  "/Franchies/chicken.webp",
  "/Franchies/franchise-bg-new.webp",
  "/Franchies/franchise-hero-bg 2.webp",
  "/Franchies/franchise-hero-bg.webp",
  "/Franchies/franchise-truck-image.webp",
  "/Franchies/fullMap.svg",
  "/Franchies/good-meat-brigher-communities.webp",
  "/Franchies/hero-main-image.webp",
  "/Franchies/hero-overlay-image.webp",
  "/Franchies/imagesec1.webp",
  "/Franchies/india-map-image.webp",
  "/Franchies/kerala-map.webp",
  "/Franchies/KeralaMap.svg",
  "/Franchies/leftBottom.webp",
  "/Franchies/marker-image.webp",
  "/Franchies/meatin-logo-text.webp",
  "/Franchies/pin.svg",
  "/Franchies/RightBottom.webp",
  "/Franchies/topRight.webp",
  "/Franchies/truck-image.webp",
  "/Home/brand-story/brand-story-icons/delivered-with-trust.svg",
  "/Home/brand-story/brand-story-icons/healthy-livestock.svg",
  "/Home/brand-story/brand-story-icons/hygienic-packaging.svg",
  "/Home/brand-story/brand-story-icons/quality-without-compromise.svg",
  "/Home/brand-story/brand-story-icons/responsible-beginnings.svg",
  "/Home/brand-story/brand-story-icons/scientific-processing.svg",
  "/Home/brand-story/images/delivered-with-trust.webp",
  "/Home/brand-story/images/healthy-livestock.webp",
  "/Home/brand-story/images/hygienic-packaging.webp",
  "/Home/brand-story/images/quality-without-compromise.webp",
  "/Home/brand-story/images/responsible-beginnings.webp",
  "/Home/brand-story/images/scientific-processing.webp",
  "/Home/certifications/fssai-icon-image.webp",
  "/Home/certifications/fssai.webp",
  "/Home/certifications/haccp-certificate-image.webp",
  "/Home/certifications/haccp-icon-image.webp",
  "/Home/certifications/halal-certificate-image.webp",
  "/Home/certifications/halal-icon-image.webp",
  "/Home/certifications/iso-certificate-image.webp",
  "/Home/certifications/iso-icon-image.webp",
  "/Home/certifications/truck-image-certificates.webp",
  "/Home/gray-bg-image.webp",
  "/Home/Hero/hero-image.webp",
  "/Home/Hero/herobg.png",
  "/Home/Hero/meat.png",
  "/Home/Screenshot 2026-08-05 182836-Photoroom 1.webp",
  "/Home/section-bg.webp",
  "/Home/truck-section/delivered-fresh-text.svg",
  "/Home/truck-section/factory-building-clean.png",
  "/Home/truck-section/factory-building.png",
  "/Home/truck-section/factory-plant-v2.png",
  "/Home/truck-section/hoock.webp",
  "/Home/truck-section/truck-body-new.webp",
  "/Home/truck-section/truck-section-bg.webp",
  "/Home/truck-section/truckWithTire.svg",
  "/logo.webp",
  "/meatin-logo.webp",
  "/MeetOurTeam/banner/banner-mobile 1.svg",
  "/MeetOurTeam/banner/banner-mobile copy.svg",
  "/MeetOurTeam/banner/banner-mobile.svg",
  "/MeetOurTeam/banner/banner.svg",
  "/MeetOurTeam/banner/food-image.webp",
  "/MeetOurTeam/banner/good-food-happens-text.webp",
  "/MeetOurTeam/banner/leflt-side-vector-design.svg",
  "/MeetOurTeam/banner/meat-images.webp",
  "/MeetOurTeam/banner/meet-our-team-banner.svg",
  "/MeetOurTeam/banner/neet-out-team-banner-people-image.png",
  "/MeetOurTeam/banner/neet-out-team-banner-people-image.webp",
  "/MeetOurTeam/banner/persons-image.webp",
  "/MeetOurTeam/banner/right-side-bg.svg",
  "/MeetOurTeam/directors-persons/Abbas Chemban.webp",
  "/MeetOurTeam/directors-persons/Anas Kamaru.webp",
  "/MeetOurTeam/directors-persons/Anfas K Mohamed.webp",
  "/MeetOurTeam/directors-persons/Arshad Asharaf.webp",
  "/MeetOurTeam/directors-persons/Hydros Villan.webp",
  "/MeetOurTeam/directors-persons/Jadeer Akthar M.webp",
  "/MeetOurTeam/directors-persons/Mohamed Asharaf K.webp",
  "/MeetOurTeam/directors-persons/Mohamed Gadhafi Pilakal.webp",
  "/MeetOurTeam/directors-persons/Mohanan Pilankuvittil.webp",
  "/MeetOurTeam/directors-persons/Moosakutty MM.webp",
  "/MeetOurTeam/directors-persons/Nasir Neriyar.webp",
  "/MeetOurTeam/directors-persons/Nazeer VM.webp",
  "/MeetOurTeam/directors-persons/Rafi Abdu Rahman.webp",
  "/MeetOurTeam/directors-persons/Rooshid Mohiyudheen C A.webp",
  "/MeetOurTeam/directors-persons/Sabeer Abdul Rahman.webp",
  "/MeetOurTeam/doodles-bg/bottom-doodle.webp",
  "/MeetOurTeam/doodles-bg/growth-image-right-side.webp",
  "/MeetOurTeam/doodles-bg/handshake-left-side.webp",
  "/MeetOurTeam/doodles-bg/left-side-growth-image.webp",
  "/MeetOurTeam/doodles-bg/right-shake-right-side.webp",
  "/MeetOurTeam/doodles-bg/support-image-hand.webp",
  "/MeetOurTeam/doodles-bg/together-piece-left-side.webp",
  "/MeetOurTeam/doodles-bg/together-piece-right-side.webp",
  "/MeetOurTeam/hero/hero-leaf-underline.svg",
  "/MeetOurTeam/hero/meet-our-team-hero-image.webp",
  "/MeetOurTeam/led-by-persons/Mr. ALI VARIKUNNATH.webp",
  "/MeetOurTeam/led-by-persons/Mr. RAFEEQUE ARAKKAKATTIL.webp",
  "/MeetOurTeam/led-by-persons/Mr. SHIBU K.MOHAMED.webp",
  "/preloader.gif",
  "/Product/Chicken/Banner/burger-patty.webp",
  "/Product/Chicken/Banner/image 282.webp",
  "/Product/Chicken/Banner/image 298 (1).webp",
  "/Product/Chicken/Banner/image 298 (2).webp",
  "/Product/Chicken/Banner/image 298 (3).webp",
  "/Product/Chicken/Banner/image 298 (4).webp",
  "/Product/Chicken/Banner/image 298.webp",
  "/Product/Chicken/beef.svg",
  "/Product/Chicken/beef.webp",
  "/Product/Chicken/bg-circle.svg",
  "/Product/Chicken/chick.svg",
  "/Product/Chicken/ChickenParts/bact.webp",
  "/Product/Chicken/ChickenParts/brest.webp",
  "/Product/Chicken/ChickenParts/drumette.webp",
  "/Product/Chicken/ChickenParts/drumstick.webp",
  "/Product/Chicken/ChickenParts/gizzard.webp",
  "/Product/Chicken/ChickenParts/heart.webp",
  "/Product/Chicken/ChickenParts/liver.webp",
  "/Product/Chicken/ChickenParts/neck.webp",
  "/Product/Chicken/ChickenParts/thig.webp",
  "/Product/Chicken/ChickenParts/wing.webp",
  "/Product/Chicken/ChickenParts/woodPlate.webp",
  "/Product/Chicken/doodle.webp",
  "/Product/Chicken/FullChicken/transparent.webp",
  "/Product/Chicken/FullChicken/withoutskin.webp",
  "/Product/Chicken/FullChicken/withskin.webp",
  "/Product/Chicken/goat.svg",
  "/Product/Chicken/goat.webp",
  "/Product/Chicken/green-hen.svg",
  "/Product/Chicken/packed-meat/back.webp",
  "/Product/Chicken/packed-meat/breast.webp",
  "/Product/Chicken/packed-meat/drumette.webp",
  "/Product/Chicken/packed-meat/drumstick.webp",
  "/Product/Chicken/packed-meat/gizzard.webp",
  "/Product/Chicken/packed-meat/heart.webp",
  "/Product/Chicken/packed-meat/liver.webp",
  "/Product/Chicken/packed-meat/neck.webp",
  "/Product/Chicken/packed-meat/thigh.webp",
  "/Product/Chicken/packed-meat/wings.webp",
  "/Product/Chicken/Platters/back.webp",
  "/Product/Chicken/Platters/bact.webp",
  "/Product/Chicken/Platters/breast.webp",
  "/Product/Chicken/Platters/drumette.webp",
  "/Product/Chicken/Platters/drumstick.webp",
  "/Product/Chicken/Platters/gizzard.webp",
  "/Product/Chicken/Platters/heart.webp",
  "/Product/Chicken/Platters/liver.webp",
  "/Product/Chicken/Platters/neck.webp",
  "/Product/Chicken/Platters/thigh.webp",
  "/Product/Chicken/Platters/wings.webp",
  "/Product/chicken-gif.gif",
  "/Product/details/360.webp",
  "/Product/details/bg.webp",
  "/Product/details/bottomCard.webp",
  "/Product/details/calories.svg",
  "/Product/details/carbs.svg",
  "/Product/details/facebook.svg",
  "/Product/details/fat.svg",
  "/Product/details/link.webp",
  "/Product/details/pack.webp",
  "/Product/details/packedProduct.webp",
  "/Product/details/protien.svg",
  "/Product/details/right aroow.svg",
  "/Product/details/section-images/arrow-bottom-left.svg",
  "/Product/details/section-images/arrow-bottom-right.svg",
  "/Product/details/section-images/arrow-top-left.svg",
  "/Product/details/section-images/arrow-top-right.svg",
  "/Product/details/section-images/benefits-texts.svg",
  "/Product/details/section-images/chef-icon.svg",
  "/Product/details/section-images/chicken-image.webp",
  "/Product/details/section-images/farm-fresh.svg",
  "/Product/details/section-images/goodness-begins-image.webp",
  "/Product/details/section-images/hygienic-processing.svg",
  "/Product/details/section-images/keep-fresh-delivered-fresh.svg",
  "/Product/details/section-images/keralas_original-meat.webp",
  "/Product/details/section-images/nutrition-information.svg",
  "/Product/details/section-images/product-details-bg.webp",
  "/Product/details/section-images/pure-natural-nutrition.webp",
  "/Product/details/section-images/quality-checked.svg",
  "/Product/details/section-images/ready-natural-taste.svg",
  "/Product/details/section-images/round-wooden-block.webp",
  "/Product/details/section-images/single-leaf-image-1.webp",
  "/Product/details/section-images/single-leaf-image-right-corner.webp",
  "/Product/details/section-images/two-leaves-images.webp",
  "/Product/GoatBeef/beef-image.webp",
  "/Product/GoatBeef/beef.svg",
  "/Product/GoatBeef/beef.webp",
  "/Product/GoatBeef/buffalo-img.webp",
  "/Product/GoatBeef/buffalo-parts.svg",
  "/Product/GoatBeef/goat-image.webp",
  "/Product/GoatBeef/goat-img.webp",
  "/Product/GoatBeef/goat-parts.svg",
  "/Product/GoatBeef/goat.svg",
  "/Product/GoatBeef/goat.webp",
  "/Product/GoatBeef/grassLand.webp",
  "/Product/GoatBeef/higinical.svg",
  "/Product/GoatBeef/natural.svg",
  "/Product/GoatBeef/perfectforRecipie.svg",
  "/Product/GoatBeef/safe.svg",
  "/Product/know-your-meat-bg.webp",
  "/Product/recipies/easy.svg",
  "/Product/recipies/leg1.webp",
  "/Product/recipies/leg2.webp",
  "/Product/recipies/leg3.webp",
  "/Product/recipies/leg4.webp",
  "/Product/recipies/rightArrow.svg",
  "/Product/recipies/servings.png",
  "/Product/recipies/time.svg",
  "/Product/slider-images/breast.webp",
  "/Product/slider-images/drumette.webp",
  "/Product/slider-images/leg-left.webp",
  "/Product/slider-images/leg-right.webp",
  "/Product/slider-images/neck.webp",
  "/Product/slider-images/slider-bg.webp",
  "/Product/slider-images/wings.webp",
  "/Product/temp-and-storage-card.webp",
  "/Recipies/back/chicken-back-soup-base.webp",
  "/Recipies/back/masala-roasted-back-cuts.webp",
  "/Recipies/back/rich-back-bone-broth.webp",
  "/Recipies/back/spicy-back-piece-curry.webp",
  "/Recipies/breast/creamy-butter-breat-curry.webp",
  "/Recipies/breast/crisppy-breast-nuggets.webp",
  "/Recipies/breast/grilled-lemon-herb-breast.webp",
  "/Recipies/breast/healthy-chicken-breast-salad.webp",
  "/Recipies/calories.webp",
  "/Recipies/cookTime.webp",
  "/Recipies/Dish/Buffalo-Wing-Platter.webp",
  "/Recipies/Dish/Chicken-Back-Soup-Base.webp",
  "/Recipies/Dish/Chicken-Heart- Pepper-Fry.webp",
  "/Recipies/Dish/Chicken-Liver-Pepper-Fry.webp",
  "/Recipies/Dish/Creamy-Butter-Breat-Curry.webp",
  "/Recipies/Dish/Cremy-Chicken-Thigh-Curry.webp",
  "/Recipies/Dish/Cremy-Liver-Pate-Spread.webp",
  "/Recipies/Dish/Crisppy-Breast-Nuggets.webp",
  "/Recipies/Dish/Crispy-Fried-Drumettes.webp",
  "/Recipies/Dish/Crispy-Fried-Thigh-Steaks.webp",
  "/Recipies/Dish/Garlic-Butter-Heart-Stir-Fry.webp",
  "/Recipies/Dish/Garlic-Butter-Liver.webp",
  "/Recipies/Dish/Garlic-Parmesan-Wings.webp",
  "/Recipies/Dish/Grilled-Lemon-Herb-Breast.webp",
  "/Recipies/Dish/Healthy-Chicken-Breast-Salad.webp",
  "/Recipies/Dish/Hearb-Roasted-Drumette-Platter.webp",
  "/Recipies/Dish/Honey-Glazed-BBQ Wings.webp",
  "/Recipies/Dish/Masala-Roasted-Back-Cuts.webp",
  "/Recipies/Dish/Nutritious-Neck-Soup.webp",
  "/Recipies/Dish/Rectangle 8410-1.webp",
  "/Recipies/Dish/Rectangle 8410.webp",
  "/Recipies/Dish/Rectangle 8411-1.webp",
  "/Recipies/Dish/Rectangle 8411.webp",
  "/Recipies/Dish/Rectangle 8412-1.webp",
  "/Recipies/Dish/Rectangle 8412.webp",
  "/Recipies/Dish/Rectangle 8413-1.webp",
  "/Recipies/Dish/Rectangle 8413.webp",
  "/Recipies/Dish/Rich-Back-Bone-Broth.webp",
  "/Recipies/Dish/Rich-Chicken-Liver.webp",
  "/Recipies/Dish/Slow-Cooked-Thigh-Roast.webp",
  "/Recipies/Dish/Smoky-Grilled-Chicken-Thigh.webp",
  "/Recipies/Dish/South-Indian-Heart-Curry.webp",
  "/Recipies/Dish/South-Indian-Neck-Fry.webp",
  "/Recipies/Dish/Spicy-Back-Piece-Curry.webp",
  "/Recipies/Dish/spicy-chicken-wnig-fry.webp",
  "/Recipies/Dish/Spicy-Heart-skewers.webp",
  "/Recipies/Dish/Spicy-Lollipop-Drumettes.webp",
  "/Recipies/Dish/Spicy-Neck-Pepper-Masala.webp",
  "/Recipies/Dish/Tangy-BBQ-Drumette-Roast.webp",
  "/Recipies/Dish/Traditional-Bone-Broth-Stock.webp",
  "/Recipies/doodle.webp",
  "/Recipies/drumette/crispy-fried-drumettes.webp",
  "/Recipies/drumette/hearb-roasted-drumette-platter.webp",
  "/Recipies/drumette/spicy-lollipop-drumettes.webp",
  "/Recipies/drumette/tangy-bbq-drumette-roast.webp",
  "/Recipies/drumstick/chettinad-drumstick-curry.webp",
  "/Recipies/drumstick/crispy-fried-drumstick-Box.webp",
  "/Recipies/drumstick/garlic-butter-glazed-leg.webp",
  "/Recipies/drumstick/spicy-thandoori-drumsticks.webp",
  "/Recipies/gizzard/crunchy-grizzard-pepper-fry.webp",
  "/Recipies/gizzard/grilled-gizzard-skewers.webp",
  "/Recipies/gizzard/pickled-gizzard-delicacy.webp",
  "/Recipies/gizzard/spicy-braised-gizzard-gravy.webp",
  "/Recipies/header/chicken-character-image.webp",
  "/Recipies/header/chicken-food-images.webp",
  "/Recipies/header/ingredient-image.webp",
  "/Recipies/header/spoon-image.webp",
  "/Recipies/heart/chicken-heart-pepper-fry.webp",
  "/Recipies/heart/garlic-butter-heart-stir-fry.webp",
  "/Recipies/heart/south-indian-heart-curry.webp",
  "/Recipies/heart/spicy-heart-skewers.webp",
  "/Recipies/leaf.webp",
  "/Recipies/leftBottomleaf.webp",
  "/Recipies/liver/chicken-liver-pepper-fry.webp",
  "/Recipies/liver/cremy-liver-pate-spread.webp",
  "/Recipies/liver/garlic-butter-liver.webp",
  "/Recipies/liver/rich-chicken-liver.webp",
  "/Recipies/neck/nutritious-neck-soup.webp",
  "/Recipies/neck/south-indian-neck-fry.webp",
  "/Recipies/neck/spicy-neck-pepper-masala.webp",
  "/Recipies/neck/traditional-bone-broth-stock.webp",
  "/Recipies/prep time.webp",
  "/Recipies/recipieChicken.webp",
  "/Recipies/reicon_food-tray.webp",
  "/Recipies/rightCenterleaf.webp",
  "/Recipies/thigh/cremy-chicken-thigh-curry.webp",
  "/Recipies/thigh/crispy-fried-thigh-steaks.webp",
  "/Recipies/thigh/slow-cooked-thigh-roast.webp",
  "/Recipies/thigh/smoky-grilled-chicken-thigh.webp",
  "/Recipies/wing/buffalo-wing-platter.webp",
  "/Recipies/wing/garlic-parmesan-wings.webp",
  "/Recipies/wing/honey-glazed-bbq-wings.webp",
  "/Recipies/wing/spicy-chicken-wing-fry.webp",
  "/Recipies/wing/spicy-chicken-wnig-fry.webp",
  "/TrustedQualityBanner/banner-bg.webp",
  "/TrustedQualityBanner/bottom-wood-block.webp",
  "/TrustedQualityBanner/character-popup.webp",
  "/TrustedQualityBanner/chicken-in-bowl.webp",
  "/TrustedQualityBanner/keralas-original-hanging.webp",
  "/TrustedQualityBanner/keralas-original-meat.webp",
  "/TrustedQualityBanner/knife-in-wooden.webp",
  "/TrustedQualityBanner/packed-chicken-products.webp",
  "/TrustedQualityBanner/person-holding-packed-chicken.webp",
  "/TrustedQualityBanner/trusted-quality-banner-img.webp",
  "/vlog/farm.jpg",
  "/vlog/hero.jpg",
  "/vlog/masterclass.jpg"
];
